export function standaloneClientScript(): string {
  return String.raw`(function () {
  var state = { snapshot: null, source: null, selectedId: null, filter: 'all', workspace: null, query: '', view: 'map', collapseIdle: false, showAllWorkspaces: false, renderedSessions: 0, renderedWorkspaces: 0, lastUpdated: null, transportError: false };
  var labels = { all: '全部', running: '运行中', waiting: '等待', idle: '空闲', completed: '已完成', interrupted: '已中断', failed: '失败', unknown: '未知' };
  var token = new URLSearchParams(location.search).get('token');
  var $ = function (id) { return document.getElementById(id); };
  var statusFilters = $('status-filters'); var workspaceFilters = $('workspace-filters'); var stateChips = $('state-chips'); var metrics = $('metrics'); var lanes = $('lanes'); var detail = $('detail'); var notice = $('notice'); var syncDot = $('sync-dot'); var syncLabel = $('sync-label'); var panelTitle = $('panel-title'); var panelSubtitle = $('panel-subtitle'); var clearWorkspace = $('clear-workspace'); var toggleWorkspaces = $('toggle-workspaces'); var resultCount = $('result-count'); var drawer = $('session-drawer'); var drawerMask = $('drawer-mask'); var collapseIdle = $('collapse-idle');
  function api(path) { return token ? path + '?token=' + encodeURIComponent(token) : path; }
  function node(tag, className, value) { var item = document.createElement(tag); if (className) item.className = className; if (value !== undefined) item.textContent = value; return item; }
  function countBy(value, key) { return value.filter(function (session) { return session.executionState === key; }).length; }
  function formatTime(value) { return new Date(value * 1000).toLocaleString('zh-CN', { hour: '2-digit', minute: '2-digit', month: 'short', day: 'numeric' }); }
  function allSessions() { return state.snapshot ? state.snapshot.sessions : []; }
  function visibleSessions() { var term = state.query.trim().toLocaleLowerCase(); return allSessions().filter(function (session) { return (state.filter === 'all' || session.executionState === state.filter) && (!state.workspace || session.cwd === state.workspace) && (!term || session.title.toLocaleLowerCase().includes(term) || session.preview.toLocaleLowerCase().includes(term)); }); }
  function setActive(button, active) { button.className = button.className.replace(/\s?active\b/g, '') + (active ? ' active' : ''); }
  function sessionButton(session, extraClass) { var card = node('button', extraClass + (state.selectedId === session.id ? ' selected' : '') + ((session.executionState === 'running' || session.executionState === 'waiting') ? ' attention' : '') + (session.forkedFromId ? ' fork' : '')); card.type = 'button'; var head = node('div', 'card-head'); head.appendChild(node('div', 'card-title', session.title)); head.appendChild(node('span', 'badge ' + session.executionState, labels[session.executionState] || '未知')); card.appendChild(head); card.appendChild(node('div', 'card-preview', session.preview || '没有可展示的摘要。')); var meta = node('div', 'card-meta'); meta.appendChild(node('span', '', '更新 ' + formatTime(session.updatedAt))); meta.appendChild(node('span', '', session.agentNickname ? session.agentNickname : 'Session')); card.appendChild(meta); if (session.forkedFromId) { var parent = allSessions().find(function (candidate) { return candidate.id === session.forkedFromId; }); card.appendChild(node('div', 'fork-note', 'Fork 自 ' + (parent ? parent.title : '不可见父 Session'))); } card.addEventListener('click', function () { state.selectedId = session.id; openDrawer(); render(); }); return card; }
  function renderMetrics() { metrics.replaceChildren(); var sessions = allSessions(); [[ '运行中', 'running', '正在接收状态事件' ], [ '已完成', 'completed', '检测到 task_complete' ], [ '已中断', 'interrupted', '检测到 turn_aborted' ], [ '全部 Session', 'all', '工作区数 ' + new Set(sessions.map(function (session) { return session.cwd || '(未提供工作目录)'; })).size ]].forEach(function (metric) { var item = node('div', 'metric'); item.appendChild(node('div', 'metric-label', metric[0])); item.appendChild(node('div', 'metric-value', String(metric[1] === 'all' ? sessions.length : countBy(sessions, metric[1])))); item.appendChild(node('div', 'metric-detail', metric[2])); metrics.appendChild(item); }); }
  function makeFilter(container, key, title, count, isActive, click, icon) { var button = node('button', 'side-item' + (isActive ? ' active' : '')); button.type = 'button'; if (icon) button.appendChild(node('span', 'side-icon', icon)); button.appendChild(node('span', '', title)); button.appendChild(node('span', 'side-tail', String(count))); button.addEventListener('click', click); container.appendChild(button); }
  function workspaceEntries(sessions) { var groups = new Map(); sessions.forEach(function (session) { var cwd = session.cwd || '(未提供工作目录)'; var current = groups.get(cwd) || { count: 0, updatedAt: 0 }; current.count += 1; current.updatedAt = Math.max(current.updatedAt, session.updatedAt); groups.set(cwd, current); }); return Array.from(groups.entries()).sort(function (a, b) { return b[1].updatedAt - a[1].updatedAt || b[1].count - a[1].count || a[0].localeCompare(b[0]); }); }
  function renderFilters() { statusFilters.replaceChildren(); var sessions = allSessions(); ['all', 'running', 'waiting', 'completed', 'interrupted', 'idle', 'failed', 'unknown'].forEach(function (key) { makeFilter(statusFilters, key, labels[key], key === 'all' ? sessions.length : countBy(sessions, key), state.filter === key, function () { state.filter = key; render(); }, key === 'all' ? '◫' : key === 'running' ? '●' : key === 'waiting' ? '◐' : key === 'completed' ? '✓' : key === 'interrupted' ? '×' : key === 'idle' ? '○' : key === 'failed' ? '!' : '?'); }); workspaceFilters.replaceChildren(); var entries = workspaceEntries(sessions); var displayed = state.showAllWorkspaces || state.workspace ? entries : entries.slice(0, 6); displayed.forEach(function (entry) { makeFilter(workspaceFilters, entry[0], entry[0], entry[1].count, state.workspace === entry[0], function () { state.workspace = state.workspace === entry[0] ? null : entry[0]; render(); }, '□'); }); if (!state.workspace && entries.length > displayed.length) { var more = node('button', 'side-item', '显示其他工作区'); more.type = 'button'; more.appendChild(node('span', 'side-tail', String(entries.length - displayed.length))); more.addEventListener('click', function () { state.showAllWorkspaces = true; render(); }); workspaceFilters.appendChild(more); } }
  function renderChips() { stateChips.replaceChildren(); ['all', 'running', 'completed', 'interrupted'].forEach(function (key) { var button = node('button', 'chip' + (state.filter === key ? ' active' : ''), labels[key]); button.type = 'button'; button.addEventListener('click', function () { state.filter = key; render(); }); stateChips.appendChild(button); }); }
  function renderMap() { lanes.replaceChildren(); state.renderedSessions = 0; state.renderedWorkspaces = 0; var sessions = visibleSessions(); if (state.collapseIdle) sessions = sessions.filter(function (session) { return session.executionState !== 'idle'; }); if (!sessions.length) { lanes.appendChild(node('div', 'empty', state.snapshot ? '没有匹配的 Session 节点。' : '正在加载快照…')); return; } var groups = new Map(); sessions.forEach(function (session) { var cwd = session.cwd || '(未提供工作目录)'; if (!groups.has(cwd)) groups.set(cwd, []); groups.get(cwd).push(session); }); var entries = Array.from(groups.entries()).sort(function (a, b) { return Math.max.apply(null, b[1].map(function (session) { return session.updatedAt; })) - Math.max.apply(null, a[1].map(function (session) { return session.updatedAt; })); }); if (!state.workspace && !state.showAllWorkspaces) entries = entries.slice(0, 6); var list = node('div', 'lane-list'); entries.forEach(function (entry) { var cwd = entry[0]; var items = entry[1]; state.renderedWorkspaces += 1; state.renderedSessions += items.length; var lane = node('section', 'lane'); var workspace = node('button', 'workspace-card' + (state.workspace === cwd ? ' active' : '')); workspace.type = 'button'; workspace.appendChild(node('div', 'workspace-title', cwd)); var active = items.filter(function (session) { return session.executionState === 'running'; }).length; var waiting = items.filter(function (session) { return session.executionState === 'waiting'; }).length; workspace.appendChild(node('div', 'workspace-summary', active + ' 运行中 · ' + waiting + ' 等待 · ' + items.length + ' 个节点')); workspace.addEventListener('click', function () { state.workspace = state.workspace === cwd ? null : cwd; render(); }); lane.appendChild(workspace); lane.appendChild(node('div', 'lane-link')); var line = node('div', 'session-line'); items.sort(function (a, b) { return b.updatedAt - a.updatedAt; }).forEach(function (session) { line.appendChild(sessionButton(session, 'map-card')); }); lane.appendChild(line); list.appendChild(lane); }); lanes.appendChild(list); }
  function renderList() { lanes.replaceChildren(); state.renderedSessions = 0; state.renderedWorkspaces = 0; var sessions = visibleSessions(); panelTitle.textContent = 'Session 列表'; panelSubtitle.textContent = '使用列表降级查看当前筛选结果'; if (!sessions.length) { lanes.appendChild(node('div', 'empty', state.snapshot ? '没有匹配的 Session。' : '正在加载快照…')); return; } state.renderedSessions = sessions.length; state.renderedWorkspaces = workspaceEntries(sessions).length; var table = node('table', 'table'); var header = node('thead'); var headerRow = node('tr'); ['SESSION', '工作区', '状态', '最近更新'].forEach(function (title) { headerRow.appendChild(node('th', '', title)); }); header.appendChild(headerRow); table.appendChild(header); var body = node('tbody'); sessions.sort(function (a, b) { return b.updatedAt - a.updatedAt; }).forEach(function (session) { var row = node('tr'); var titleCell = node('td'); var button = node('button', 'table-title', session.title); button.type = 'button'; button.addEventListener('click', function () { state.selectedId = session.id; openDrawer(); render(); }); titleCell.appendChild(button); row.appendChild(titleCell); row.appendChild(node('td', '', session.cwd || '—')); var statusCell = node('td'); statusCell.appendChild(node('span', 'badge ' + session.executionState, labels[session.executionState] || '未知')); row.appendChild(statusCell); row.appendChild(node('td', '', formatTime(session.updatedAt))); body.appendChild(row); }); table.appendChild(body); lanes.appendChild(table); }
  function renderDetail() { detail.replaceChildren(); var session = allSessions().find(function (candidate) { return candidate.id === state.selectedId; }); if (!session) { detail.className = 'detail-empty'; detail.textContent = '选择泳道中的 Session 节点，即可查看此数据源已确认的基础字段。'; return; } detail.className = ''; detail.appendChild(node('div', 'detail-session', session.title)); [['执行状态', labels[session.executionState] || '未知'], ['最近更新', formatTime(session.updatedAt)], ['工作目录', session.cwd || '—'], ['摘要', session.preview || '—'], ['Session ID', session.sessionId], ['派生关系', session.forkedFromId ? 'Fork 自 ' + session.forkedFromId : '未报告派生关系']].forEach(function (row) { var group = node('div', 'detail-row'); group.appendChild(node('div', 'detail-label', row[0])); group.appendChild(node('div', 'detail-value', row[1])); detail.appendChild(group); }); detail.appendChild(node('p', 'detail-boundary', '此独立 Reader 仅展示当前数据源已确认的字段；不显示或推断项目归属、置顶、归档、Token、计划、子 Agent 与完整对话内容。')); }
  function updateConnection() { var sync = state.snapshot && state.snapshot.sync; var phase = state.transportError ? 'error' : sync ? sync.phase : 'error'; notice.className = 'connection-note' + (phase === 'ready' ? '' : phase === 'error' ? ' error' : ' stale'); syncDot.className = 'sync-dot ' + (phase === 'ready' ? 'ready' : phase === 'error' ? 'error' : 'stale'); if (!state.snapshot) { notice.textContent = '无法连接本地 Map Reader；不会建立第二条连接去伪造与 Codex Desktop 的同步。'; syncLabel.textContent = 'Reader 未连接'; return; } if (phase === 'ready') { if (state.source && state.source.kind === 'filesystem-compat') { notice.textContent = '本地兼容模式：每秒只读检查 Codex session 事件文件；未呈现对话正文，非官方接口。'; syncLabel.textContent = '本地兼容同步'; return; } notice.textContent = '已获取最新完整快照 · 来源由 Codex Maps 独立持有，未与当前 Codex Desktop 共享连接。'; syncLabel.textContent = 'SSE 已连接'; return; } notice.textContent = '连接已断开或快照过期；以下内容来自 ' + (state.lastUpdated ? state.lastUpdated.toLocaleString('zh-CN') : '最后一次更新') + ' 的最后完整快照。'; syncLabel.textContent = '最后完整快照'; }
  function render() { renderMetrics(); renderFilters(); renderChips(); panelTitle.textContent = state.view === 'map' ? '工作区泳道地图' : 'Session 列表'; panelSubtitle.textContent = state.view === 'map' ? '工作区是泳道 · Session 是节点 · Fork 以虚线节点标识' : '使用列表降级查看当前筛选结果'; if (state.view === 'map') renderMap(); else renderList(); renderDetail(); updateConnection(); clearWorkspace.hidden = !state.workspace; toggleWorkspaces.hidden = state.view !== 'map' || !!state.workspace; toggleWorkspaces.textContent = state.showAllWorkspaces ? '只看重点工作区' : '显示全部工作区'; collapseIdle.textContent = state.collapseIdle ? '展开空闲节点' : '折叠空闲节点'; resultCount.textContent = '显示 ' + state.renderedSessions + ' / ' + visibleSessions().length + ' 个 Session · ' + state.renderedWorkspaces + ' / ' + workspaceEntries(visibleSessions()).length + ' 个工作区'; setActive($('view-map'), state.view === 'map'); setActive($('view-list'), state.view === 'list'); }
  function openDrawer() { drawer.classList.add('open'); drawerMask.classList.add('open'); drawer.setAttribute('aria-hidden', 'false'); }
  function closeDrawer() { drawer.classList.remove('open'); drawerMask.classList.remove('open'); drawer.setAttribute('aria-hidden', 'true'); }
  function apply(envelope) { state.snapshot = envelope.snapshot; state.source = envelope.source; state.transportError = false; state.lastUpdated = new Date(); if (state.selectedId && !allSessions().some(function (session) { return session.id === state.selectedId; })) { state.selectedId = null; closeDrawer(); } render(); }
  $('search').addEventListener('input', function (event) { state.query = event.target.value; render(); }); $('view-map').addEventListener('click', function () { state.view = 'map'; render(); }); $('view-list').addEventListener('click', function () { state.view = 'list'; render(); }); collapseIdle.addEventListener('click', function () { state.collapseIdle = !state.collapseIdle; render(); }); toggleWorkspaces.addEventListener('click', function () { state.showAllWorkspaces = !state.showAllWorkspaces; render(); }); clearWorkspace.addEventListener('click', function () { state.workspace = null; render(); }); $('close-drawer').addEventListener('click', closeDrawer); drawerMask.addEventListener('click', closeDrawer); document.addEventListener('keydown', function (event) { if (event.key === 'Escape') closeDrawer(); });
  fetch(api('/api/snapshot')).then(function (response) { if (!response.ok) throw new Error('snapshot unavailable'); return response.json(); }).then(apply).catch(function () { state.snapshot = null; render(); }); var events = new EventSource(api('/api/events')); events.addEventListener('snapshot', function (event) { apply(JSON.parse(event.data)); }); events.onerror = function () { if (state.snapshot) { state.transportError = true; render(); } };
})();`;
}
